### ISSUE TITLE
[Question] Web Design Tool

### ISSUE THREAD

**Issue by alexandesigner** [tipeio/tipe#124]
How amazing this project!!! 

I would like to know if in addition to the CMS will have a Web Design tool feature, ie .. something like [Webflow Designer](https://webflow.com/designer) would be awesome and I would be willing to contribute.

... or in the case the project will be exclusively focused on content management abstracting the design part of the project

👍  Best regards!

**Comment by gdi2290** [comment]
We won't offer one but we will be able to integrate with all of the Web Design tools out there. For example [haiku](https://www.haiku.ai/) and [pagedraw](https://pagedraw.io/) are a couple examples.
