### ISSUE TITLE
Can't sign in to existing repo

### ISSUE THREAD

**Issue by sisterjones** [tipeio/tipe#126]
I have an existing repo that I've been using for a react app cms, and as of yesterday - I've been unable to signin. 

I go through the auth steps, and get hit with 'Something went wrong' as an error state below the user/pw fields. 

Any insight as to what might be going on here?

**Comment by gdi2290** [comment]
yeah, can we jump on video call tomorrow? you might need to clear the index.html cache for tipe.io

**Comment by sisterjones** [comment]
sorry for my delay - if you're still available for a call tomorrow (Monday, 8/6) that would be awesome. 

Thanks so much for getting back to me so quickly.

**Comment by sisterjones** [comment]
Update --

No need for a call. I followed your advice regarding the index.html cache and was able to get into my account. That was the exact issue I was having. 

Thank you thank you!

**Comment by gdi2290** [comment]
awesome! yeah sorry about that.
